import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PROJECT_MEMORY_FILE } from '@contextosai/shared';
import { ContextDatabase } from './database.js';
import { getContextOSPath, loadConfig } from './config.js';
import { readFileSync } from 'node:fs';

const CURSOR_RULE_PATH = '.cursor/rules/contextos.mdc';
const AGENTS_MD = 'AGENTS.md';

export function readProjectMemoryContent(rootPath: string): string {
  try {
    return readFileSync(join(getContextOSPath(rootPath), PROJECT_MEMORY_FILE), 'utf-8');
  } catch {
    return 'No project memory yet. Run `contextosai index`.';
  }
}

export function buildAgentContextContent(rootPath: string, db: ContextDatabase): string {
  const rules = db.getRules();
  const decisions = db.getDecisions().slice(0, 10);
  const stats = db.getStats();

  const lines: string[] = [
    '---',
    'description: ContextOS project memory — architecture, conventions, and decisions',
    'alwaysApply: true',
    '---',
    '',
    '# ContextOS Project Memory',
    '',
    `> Auto-generated by ContextOS. Files indexed: ${stats.filesIndexed}. Last indexed: ${stats.lastIndexedAt ?? 'never'}.`,
    '',
  ];

  const frameworks = rules.filter((r) => r.category === 'framework');
  const conventions = rules.filter((r) => r.category === 'convention');
  const modules = rules.filter((r) => r.category === 'module');

  if (frameworks.length) {
    lines.push('## Frameworks', '');
    for (const f of frameworks) {
      lines.push(`- **${f.name}**: ${f.description}`);
    }
    lines.push('');
  }

  if (conventions.length) {
    lines.push('## Conventions', '');
    for (const c of conventions) {
      lines.push(`- ${c.name}: ${c.description}`);
    }
    lines.push('');
  }

  if (modules.length) {
    lines.push('## Important Modules', '');
    for (const m of modules) {
      lines.push(`- **${m.name}**: ${m.description}`);
    }
    lines.push('');
  }

  if (decisions.length) {
    lines.push('## Recent Architectural Decisions', '');
    for (const d of decisions) {
      lines.push(
        `- **${d.title}**: ${d.decision} _(confidence: ${(d.confidence * 100).toFixed(0)}%)_`,
      );
    }
    lines.push('');
  }

  lines.push('## Project Overview', '');
  lines.push(readProjectMemoryContent(rootPath));

  return lines.join('\n');
}

export function exportAgentContext(rootPath: string, db: ContextDatabase): void {
  const config = loadConfig(rootPath);
  if (config.agentExportEnabled === false) return;

  const content = buildAgentContextContent(rootPath, db);
  const cursorDir = join(rootPath, '.cursor', 'rules');
  if (!existsSync(cursorDir)) {
    mkdirSync(cursorDir, { recursive: true });
  }
  writeFileSync(join(rootPath, CURSOR_RULE_PATH), content, 'utf-8');
  const agentsContent = content.replace(/^---[\s\S]*?---\n\n/, '');
  writeFileSync(join(rootPath, AGENTS_MD), agentsContent, 'utf-8');
}

export function exportAgentContextOnly(rootPath: string): void {
  const db = new ContextDatabase(rootPath);
  try {
    exportAgentContext(rootPath, db);
  } finally {
    db.close();
  }
}
